# Generated by Django 2.0.1 on 2018-01-11 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalClinicUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('a', 'Admin'), ('d', 'Dentist'), ('p', 'Patient')], default='p', max_length=1)),
                ('bod', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DentalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_breath', models.BooleanField(default=False)),
                ('sensitive_teeth', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DentalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('dental_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dental_clinic_x.DentalHistory')),
                ('dentists', models.ManyToManyField(related_name='dentists', to='dental_clinic_x.DentalClinicUser')),
            ],
        ),
        migrations.CreateModel(
            name='DentalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('dental_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_clinic_x.DentalRecord')),
                ('dental_services', models.ManyToManyField(to='dental_clinic_x.DentalService')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_clinic_x.DentalClinicUser')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operations', models.BooleanField(default=False)),
                ('nursing', models.BooleanField(default=False)),
                ('pregnant', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='medical_history',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dental_clinic_x.MedicalHistory'),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='dental_clinic_x.DentalClinicUser'),
        ),
    ]
