# Generated by Django 2.0 on 2018-01-20 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalClinicUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('a', 'Admin'), ('d', 'Dentist'), ('p', 'Patient'), ('u', 'Unknown')], default='u', max_length=1)),
                ('bod', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DentalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('medical_history_operations', models.BooleanField(default=False)),
                ('medical_history_nursing', models.BooleanField(default=False)),
                ('medical_history_pregnant', models.BooleanField(default=False)),
                ('dental_history_bad_breath', models.BooleanField(default=False)),
                ('dental_history_sensitive_teeth', models.BooleanField(default=False)),
                ('dentists', models.ManyToManyField(related_name='dentists', to='dental_clinic_x.DentalClinicUser')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='dental_clinic_x.DentalClinicUser')),
            ],
        ),
        migrations.CreateModel(
            name='DentalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('VND', 'Vietnam Dong')], max_length=3, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DentalServiceQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dental_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_clinic_x.DentalService')),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('dental_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_clinic_x.DentalRecord')),
                ('dental_services', models.ManyToManyField(through='dental_clinic_x.DentalServiceQuantity', to='dental_clinic_x.DentalService')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_clinic_x.DentalClinicUser')),
            ],
        ),
        migrations.AddField(
            model_name='dentalservicequantity',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_clinic_x.Examination'),
        ),
    ]
