# Generated by Django 2.0.1 on 2018-01-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_clinic_x', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentalrecord',
            old_name='dental_history_nursing',
            new_name='dental_history_bad_breath',
        ),
        migrations.RenameField(
            model_name='dentalrecord',
            old_name='dental_history_operations',
            new_name='dental_history_sensitive_teeth',
        ),
        migrations.RenameField(
            model_name='dentalrecord',
            old_name='dental_history_pregnant',
            new_name='medical_history_nursing',
        ),
        migrations.RenameField(
            model_name='dentalrecord',
            old_name='medical_history_bad_breath',
            new_name='medical_history_operations',
        ),
        migrations.RenameField(
            model_name='dentalrecord',
            old_name='medical_history_sensitive_teeth',
            new_name='medical_history_pregnant',
        ),
        migrations.AlterField(
            model_name='dentalclinicuser',
            name='role',
            field=models.CharField(choices=[('a', 'Admin'), ('d', 'Dentist'), ('p', 'Patient'), ('u', 'Unknown')], default='u', max_length=1),
        ),
        migrations.AlterField(
            model_name='dentalrecord',
            name='dentists',
            field=models.ManyToManyField(null=True, related_name='dentists', to='dental_clinic_x.DentalClinicUser'),
        ),
    ]
