# Generated by Django 2.0 on 2018-01-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_clinic_x', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalservice',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('VND', 'Vietnam Dong')], default='USD', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dentalservice',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dentalservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dentalservicequantity',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
