# Generated by Django 2.0.1 on 2018-01-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_clinic_x', '0002_auto_20180117_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalservice',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('VND', 'Vietnam Dong')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dentalrecord',
            name='dentists',
            field=models.ManyToManyField(related_name='dentists', to='dental_clinic_x.DentalClinicUser'),
        ),
        migrations.AlterField(
            model_name='dentalservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
